#!/bin/bash

file_name="2_create_and_insert.py"

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
python_file="$(realpath "$SCRIPT_PATH/../../python/nested_data/$file_name")"

submit_job() {
	spark-submit \
		--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
		--conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog \
		--conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog \
		--conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
		--conf spark.sql.catalog.glue_catalog.warehouse=s3://iceberg-example-huge-head-li/pyspark/ \
		--conf spark.sql.iceberg.check-ordering=false \
		"$1"
}

echo $python_file
time submit_job "$python_file"
