#!/bin/bash

file_name="2_insert_nested_data.py"

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
python_file="$(realpath "$SCRIPT_PATH/../../python/nested_data/$file_name")"

echo $python_file
time spark-submit $python_file