apiVersion: v1
kind: Pod
metadata:
  name: one-time-task
  namespace: default
spec:
  serviceAccountName: default-service-account
  automountServiceAccountToken: true
  containers:
  - name: one-time-task
    image: 939653976686.dkr.ecr.us-east-1.amazonaws.com/example_ecr_repository:step-app
    env:
      - name: LOG_REGION
        value: "${LOG_REGION}"
      - name: LOG_GROUP_NAME
        value: "${LOG_GROUP_NAME}"
      - name: LOG_STREAM_PERIOD_MINUTES
        value: "30"
    imagePullPolicy: Always
  restartPolicy: Never