-- ORACLE.STUDENT definition

DROP TABLE ORACLE.STUDENT;

CREATE TABLE ORACLE.STUDENT 
(	
	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY NOT NULL, 
	"NAME" VARCHAR2(100), 
	 CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ID")
);

INSERT INTO ORACLE.STUDENT (name) VALUES('Song Li');
INSERT INTO ORACLE.STUDENT (name) VALUES('Joe Bidden');
INSERT INTO ORACLE.STUDENT (name) VALUES('Donald Trump');


SELECT * FROM ORACLE.STUDENT;