#!/bin/bash

what=$1
if [ -z "${what}" ]
then
    echo "default to apply"
    what="a"
fi

case "${what}" in
    "a")
        export LOG_REGION="us-east-1"
        export LOG_GROUP_NAME="step-app"

        envsubst < deployment-pod.yaml | kubectl apply -f -
        ;;
    "d")
        kubectl delete -f deployment-pod.yaml
        ;;
    *)
        echo "Nothing to do for ${what}. Available options: a, d"
        ;; 
esac