#!/bin/bash

cluster="ASimpleCluster"

oidc_id=$(aws eks describe-cluster --name ${cluster} --query "cluster.identity.oidc.issuer" --output text | cut -d '/' -f 5)
exists=$(aws iam list-open-id-connect-providers | grep $oidc_id | cut -d "/" -f4)

if [ -n "${exists}" ]
then
  echo "An IAM OIDC provider for the cluster already exists"
else
  eksctl utils associate-iam-oidc-provider --cluster ${cluster} --approve
fi

eksctl create iamserviceaccount --name default-service-account \
  --namespace default \
  --cluster ${cluster} \
  --override-existing-serviceaccounts \
  --role-name ${cluster}-default-service-account-role \
  --attach-policy-arn arn:aws:iam::939653976686:policy/eks-a-simple-cluter-sa-policy \
  --approve

eksctl create iamserviceaccount --name aws-load-balancer-controller \
  --namespace kube-system \
  --cluster ${cluster} \
  --override-existing-serviceaccounts \
  --role-name ${cluster}-default-service-account-alb-ctrl-role \
  --attach-policy-arn arn:aws:iam::939653976686:policy/eks-a-simple-cluter-alb-controller-policy \
  --approve

