#!/bin/bash

cluster="a_simple_cluster"

oidc_id=$(aws eks describe-cluster --name ${cluster} --query "cluster.identity.oidc.issuer" --output text | cut -d '/' -f 5)
exists=$(aws iam list-open-id-connect-providers | grep $oidc_id | cut -d "/" -f4)

if [ -n "${exists}" ]
then
  echo "An IAM OIDC provider for the cluster already exists"
else
  eksctl utils associate-iam-oidc-provider --cluster ${cluster} --approve
fi