#!/bin/bash

cluster="ASimpleCluster"

# delete the service accounts
eksctl delete iamserviceaccount \
    --region us-east-1 \
    --name default-service-account \
    --namespace default \
    --cluster ${cluster}

eksctl delete iamserviceaccount \
    --region us-east-1 \
    --name aws-load-balancer-controller \
    --namespace kube-system \
    --cluster ${cluster}

resources=$(aws resourcegroupstaggingapi get-resources \
    --tag-filters Key=alpha.eksctl.io/cluster-name,Values=${cluster} \
    --resource-type-filters "iam:oidc-provider")

list=$(echo ${resources} | jq '.ResourceTagMappingList')

lengh=$(echo ${list} | jq length)
if [ "${lengh}" -eq "0" ]; then
   echo "No associated iam:oidc-provider found. Skipping"
fi


# delete the openid providers associated to the cluster
echo ${list} | jq -c '.[]' | while read i; do
    arn=$(echo $i | jq '.ResourceARN')
    arn=${arn//\"/}
    
    aws iam delete-open-id-connect-provider \
        --open-id-connect-provider-arn ${arn}

    echo "deleted ${arn}"
done

