#!/bin/bash

what=$1
if [ -z "${what}" ]
then
    echo "default action to plan"
    what="p"
fi

case "${what}" in
    "i")
        terraform init -reconfigure
        ;;
    "p")
        terraform plan
        ;;
    "a")
        terraform apply -auto-approve
        ;;
    "d")
        terraform destroy -auto-approve
        ;;
    *)
        echo "Nothing to do for ${what}. Available options: i,p,a,d"
        ;; 
esac