#!/bin/bash

CLUSTER="basic-example-cluster"
TASK_DEFINITION="basic-example-task-definition"

SG="sg-0a37f508df8bc1013"
SUBNETS="subnet-0147708743f846781, subnet-0e03c55d21b9dea8d"

task_raw=$(aws ecs run-task \
    --task-definition ${TASK_DEFINITION} \
    --launch-type FARGATE \
    --cluster ${CLUSTER} \
    --network-configuration \
      "awsvpcConfiguration={subnets=[${SUBNETS}],securityGroups=[${SG}],assignPublicIp=ENABLED}")

taskArn=$(echo $task_raw | jq '.tasks[0].taskArn')

echo -e "Task Started\n$taskArn"

