#!/bin/bash

# https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-secrets-manager.html#rds-secrets-manager-rotate-db-cluster

export CLUSTER="arn:aws:rds:us-east-1:939653976686:cluster:aurora-cluster"

python python/rotate-aurora-password.py