#!/bin/bash

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
source $SCRIPT_PATH/common

# It is possible to pass query string parameters without special configurations
# It is ok to be with or without the last "/" after "sect-2"
URL="$URL_BASE/sect-1/the-parameter-1/sect-2/?q=abcd"

# authorization header is required
# Check the terraform on the "apigw-step-3-authorizer.tf" file
TOKEN="abcd"
curl -i -H "Authorization: Bearer $TOKEN" ${URL}

echo
