#!/bin/bash

file_name="run.py"

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
python_file="$(realpath "$SCRIPT_PATH/../../python/schema_test/$file_name")"

submit_job() {
	spark-submit "$1"
}

echo $python_file
time submit_job "$python_file"
