#!/bin/bash


SCRIPT_PATH="$(realpath "$(dirname -- "${BASH_SOURCE[0]}")")"

HOST_GLUE_WORKSPACE="$SCRIPT_PATH/../../../glue"
CONTAINER_GLUE_WORKSPACE="/home/hadoop/workspace/"

IMAGE="public.ecr.aws/glue/aws-glue-libs:5.1.0"
CONTAINER_NAME="glue_libs_5.0_iceberg_example"

if [ "$1" == "-d" ]; then
    read -p "Are you sure to delete the docker container $CONTAINER_NAME? (y/N) " -n 1 -r

    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        if [ "$(docker container ls -a | grep "$CONTAINER_NAME")" ]; then
            echo -e "\nClearing the $CONTAINER_NAME"
            docker container rm -v "$CONTAINER_NAME"
        else
            echo -e "\n$CONTAINER_NAME does not exist"
        fi
    fi

    exit 0
fi

if [ ! "$(docker container ls -a | grep "$CONTAINER_NAME")" ]; then
    docker run -it \
        -v $HOST_GLUE_WORKSPACE:$CONTAINER_GLUE_WORKSPACE:rw \
        -v ~/.aws:/home/hadoop/.aws:ro \
        -w $CONTAINER_GLUE_WORKSPACE \
        --name "$CONTAINER_NAME" \
        "$IMAGE"

else
    docker container start -i "$CONTAINER_NAME"
fi
