version: "3.8"
services:
  postgres:
    image: postgres:14.9
    container_name: psycopg3-example
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres