#!/bin/bash

what=$1
if [ -z "${what}" ]; then
    echo "default action to plan"
    what="p"
fi

cd terraform

init() {
    terraform init -reconfigure -upgrade
}

case "${what}" in
"p")
    init
    terraform plan
    ;;
"a")
    init
    terraform apply -auto-approve
    ;;
"d")
    init
    terraform destroy -auto-approve
    ;;
*)
    echo "Nothing to do for ${what}. Available options: p,a,d"
    ;;
esac
