#!/bin/bash

SCRIPT_FILE=$(basename "$0")

red() {
    echo '\033[1;31m'$1'\033[0m'
}

TARGET_DIRECTORY_NAME=".env-3*"

WHAT=$1
case "$WHAT" in
list | l)
    find . -type d -name ".env-3*" -print
    ;;
delete | d)
    find . -type d -name "$TARGET_DIRECTORY_NAME" -print | xargs -I {} rm -rf {}
    find . -type d -name "$TARGET_DIRECTORY_NAME" -print
    ;;
*)
    echo -e "This command deletes the $TARGET_DIRECTORY_NAME directories that take large disk spaces"
    echo -e "Only the following operations are supported:\n"
    echo -e "$SCRIPT_FILE $(red l) | list - list all the $TARGET_DIRECTORY_NAME directories"
    echo -e "$SCRIPT_FILE $(red d) | delete - delete all the $TARGET_DIRECTORY_NAME directories"
    exit 1
    ;;
esac
