#!/bin/bash

SCRIPT_PATH="$(realpath "$(dirname -- "${BASH_SOURCE[0]}")")"

HOST_GLUE_WORKSPACE="$SCRIPT_PATH/../../../glue"
CONTAINER_GLUE_WORKSPACE="/home/glue_user/workspace"

IMAGE="amazon/aws-glue-libs:glue_libs_4.0.0_image_01"
CONTAINER_NAME="glue_libs_4.0.0_image_01_iceberg_example"

CONTAINER_EXITS="$(docker container ls -a | grep "$CONTAINER_NAME")"

if [ "$1" == "-d" ]; then
    read -p "Are you sure to delete the docker container $CONTAINER_NAME? (y/N) " -n 1 -r

    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        if [ "$CONTAINER_EXITS" ]; then
            echo -e "\nClearing the $CONTAINER_NAME"
            docker container rm -v "$CONTAINER_NAME"
        else
            echo -e "\n$CONTAINER_NAME does not exist"
        fi
    fi

    exit 0
fi

if [ ! "$CONTAINER_EXITS" ]; then

    docker run -it \
        -v $HOST_GLUE_WORKSPACE:$CONTAINER_GLUE_WORKSPACE:rw \
        -e DISABLE_SSL=true \
        -e DATALAKE_FORMATS=hudi,delta,iceberg \
        -p 4040:4040 \
        -p 8888:8888 \
        -p 18080:18080 \
        --name "$CONTAINER_NAME" \
        --add-host "host.docker.internal:host-gateway" \
        -w $CONTAINER_GLUE_WORKSPACE \
        "$IMAGE"

else
    docker container start -i "$CONTAINER_NAME"
fi
