#!/bin/bash

# The work-group can limit the events received by the event target
aws athena start-query-execution \
    --query-string "select * from simple_athena_database.example_data" \
    --result-configuration OutputLocation=s3://example.huge.head.li.2023/example_data/ \
    --work-group test-athena-work-group
