#!/bin/bash

git reset --soft HEAD~
git add-commit -m "Updated the aws-terraform-examples"
git push -f

echo && git fetch
echo -e "Wait for a second ...\n" && sleep 1

echo && echo "Changes in the last commit:"
git diff HEAD~1 HEAD --name-only && echo

git log -2