#!/bin/bash

JOB_NAME="AWS_BATCH_EXAMPLE"
JOB_QUEUE="aws-batch-basic-example-job-queue"
JOB_DEFINITION="aws-batch-basic-example-job-definition"

aws batch submit-job \
  --job-name  $JOB_NAME \
  --job-queue $JOB_QUEUE \
  --job-definition $JOB_DEFINITION

