#!/bin/bash -e

what=$1
if [ -z "${what}" ]; then
	echo "default action to plan"
	what="p"
fi

cd terraform

terraform init -reconfigure -upgrade

case "${what}" in
"p")
	terraform plan -detailed-exitcode
	TERRAFORM_EXIT_CODE=$?
	if [[ "$TERRAFORM_EXIT_CODE" == "0" ]]; then
		echo "outputs:"
		terraform output
	fi
	;;
"a")
	terraform apply -auto-approve
	;;
"d")
	terraform destroy -auto-approve
	;;
*)
	echo "Nothing to do for ${what}. Available options: p,a,d"
	;;
esac
