#!/bin/bash -e

# Need the following information
# 1. The lambda name
# 2. The directory of the lambda source code
# 3. The temporary folder to do the work. The source code it copied to the workspace so it does not affect the soure directory

LAMBDA="awswrangler_example"
LAMBDA_DIR="/home/song/Sandbox/aws-terraform-examples/lambda-examples/awswrangler/lambdas/awswrangler_example"
WORKSPACE="/home/song/Sandbox/aws-terraform-examples/.zip"

(
    rm -rf $WORKSPACE && mkdir -p $WORKSPACE
    cp -r $LAMBDA_DIR $WORKSPACE/lambda
)

(
    REQUIREMENTS="requirements.txt"
    cd $WORKSPACE/lambda

    if [ -f "$REQUIREMENTS" ]; then
        if ! [ -x "$(command -v pip)" ]; then
            echo 'pip is not installed, we need pip to create the deployment package' >&2
            exit 1
        fi

        # pip install -r "$REQUIREMENTS" -q -t .
        pip install -r "$REQUIREMENTS" -q -t . --platform=manylinux2014_x86_64 --only-binary=:all:
    fi

    find . -type d -name "__pycache__" -exec rm -rf {} +
    find . -type d -name "*.dist-info" -exec rm -rf {} +
    rm -f $REQUIREMENTS

    ZIP_FILE="../lambda.zip"
    zip -rq $ZIP_FILE . && du -h $ZIP_FILE && echo "Created the deployment package"
)

(
    cd $WORKSPACE
    echo "Updating the lambda function: $LAMBDA"
    aws lambda update-function-code \
        --region us-east-1 \
        --function-name "$LAMBDA" \
        --zip-file fileb://lambda.zip 1>/dev/null

    echo "Waiting for the update to complete..."
    aws lambda wait function-updated --function-name $LAMBDA

    echo "Done"
)

(
    rm -rf $WORKSPACE
)
