#!/bin/bash

file_name="4_upsert_and_delete.py"

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
python_file="$(realpath "$SCRIPT_PATH/../../python/flat_table/$file_name")"

echo $python_file
time spark-submit $python_file